# Add blank line
add_newline = true

# 
"$schema" = 'https://starship.rs/config-schema.json'

format ="""
[┌──](bold green)$directory$rust$package$git_branch$git_status$python
[└─>](bold green)"""

[package]
disabled = false

[python]
symbol = ' '
